name: Dev documentation

on:
  push:
    branches:
      - 'dev'
    tags-ignore:
      - '**'

jobs:
  dev-docs:
    if: "!contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Configure workflow
        id: configuration
        env:
          DOCS_DEPLOY_KEY: ${{ secrets.DOCS_DEPLOY_KEY }}
        run: |
          if [ -n "$DOCS_DEPLOY_KEY" ]
          then
            echo "DOCS_DEPLOY_KEY_PRESENT=true" >> $GITHUB_OUTPUT
          else
            echo "Secret 'DOCS_DEPLOY_KEY' not present. Exiting job."
          fi
          BRANCH_NAME="${GITHUB_REF#refs/*/}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "DOCS_OUTPUT_DIR=${GITHUB_WORKSPACE}/worldchatter-docs/docs/dev/${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "DOCS_REPO_DIR=${GITHUB_WORKSPACE}/worldchatter-docs" >> $GITHUB_OUTPUT
          echo "PLUGIN_REPO_DIR=${GITHUB_WORKSPACE}/worldchatter" >> $GITHUB_OUTPUT
      - name: Checkout WorldChatter
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: worldchatter
      - name: Setup documentation environment
        if: steps.configuration.outputs.DOCS_DEPLOY_KEY_PRESENT == 'true'
        uses: ./worldchatter/.github/workflows/docs/setup-docs
        with:
          docs_deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
          docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
      - name: Generate documentation
        id: generate
        if: steps.configuration.outputs.DOCS_DEPLOY_KEY_PRESENT == 'true'
        uses: ./worldchatter/.github/workflows/docs/generate-docs
        with:
          docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
          docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
          plugin_repo_dir: ${{ steps.configuration.outputs.PLUGIN_REPO_DIR }}
      - name: Push dev documentation
        if: steps.generate.outputs.DOCS_CHANGED == 'true'
        uses: ./worldchatter/.github/workflows/docs/push-docs
        with:
          docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
          git_name: Dev Docs Bot
          git_email: devdocs@worldchatter.org
          git_commit_message: "Update ${{ steps.configuration.outputs.BRANCH_NAME }} branch dev docs to ${{ github.repository }}@${{ github.sha }}"
